/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContainerUnloadingNewJerseyRouteImport } from './routes/container-unloading-new-jersey'
import { Route as CrossDockNewJerseyRouteImport } from './routes/cross-dock-new-jersey'
import { Route as FulfillmentNewJerseyRouteImport } from './routes/fulfillment-new-jersey'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PalletRestackingNewJerseyRouteImport } from './routes/pallet-restacking-new-jersey'
import { Route as PalletStorageNewJerseyRouteImport } from './routes/pallet-storage-new-jersey'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TerminalAtTheDockRouteImport } from './routes/terminal-at-the-dock'
import { Route as TerminalAtTheGateRouteImport } from './routes/terminal-at-the-gate'
import { Route as TerminalInTheYardRouteImport } from './routes/terminal-in-the-yard'
import { Route as TransloadingNewJerseyRouteImport } from './routes/transloading-new-jersey'
import { Route as WhatIsTerminalYosRouteImport } from './routes/what-is-terminal-yos'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainerUnloadingNewJerseyRoute =
  ContainerUnloadingNewJerseyRouteImport.update({
    id: '/container-unloading-new-jersey',
    path: '/container-unloading-new-jersey',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossDockNewJerseyRoute = CrossDockNewJerseyRouteImport.update({
  id: '/cross-dock-new-jersey',
  path: '/cross-dock-new-jersey',
  getParentRoute: () => rootRouteImport,
} as any)
const FulfillmentNewJerseyRoute = FulfillmentNewJerseyRouteImport.update({
  id: '/fulfillment-new-jersey',
  path: '/fulfillment-new-jersey',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PalletRestackingNewJerseyRoute =
  PalletRestackingNewJerseyRouteImport.update({
    id: '/pallet-restacking-new-jersey',
    path: '/pallet-restacking-new-jersey',
    getParentRoute: () => rootRouteImport,
  } as any)
const PalletStorageNewJerseyRoute = PalletStorageNewJerseyRouteImport.update({
  id: '/pallet-storage-new-jersey',
  path: '/pallet-storage-new-jersey',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalAtTheDockRoute = TerminalAtTheDockRouteImport.update({
  id: '/terminal-at-the-dock',
  path: '/terminal-at-the-dock',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalAtTheGateRoute = TerminalAtTheGateRouteImport.update({
  id: '/terminal-at-the-gate',
  path: '/terminal-at-the-gate',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalInTheYardRoute = TerminalInTheYardRouteImport.update({
  id: '/terminal-in-the-yard',
  path: '/terminal-in-the-yard',
  getParentRoute: () => rootRouteImport,
} as any)
const TransloadingNewJerseyRoute = TransloadingNewJerseyRouteImport.update({
  id: '/transloading-new-jersey',
  path: '/transloading-new-jersey',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsTerminalYosRoute = WhatIsTerminalYosRouteImport.update({
  id: '/what-is-terminal-yos',
  path: '/what-is-terminal-yos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/container-unloading-new-jersey': typeof ContainerUnloadingNewJerseyRoute
  '/cross-dock-new-jersey': typeof CrossDockNewJerseyRoute
  '/fulfillment-new-jersey': typeof FulfillmentNewJerseyRoute
  '/markets': typeof MarketsRoute
  '/pallet-restacking-new-jersey': typeof PalletRestackingNewJerseyRoute
  '/pallet-storage-new-jersey': typeof PalletStorageNewJerseyRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminal-at-the-dock': typeof TerminalAtTheDockRoute
  '/terminal-at-the-gate': typeof TerminalAtTheGateRoute
  '/terminal-in-the-yard': typeof TerminalInTheYardRoute
  '/transloading-new-jersey': typeof TransloadingNewJerseyRoute
  '/what-is-terminal-yos': typeof WhatIsTerminalYosRoute
  '/api/quote': typeof ApiQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/container-unloading-new-jersey': typeof ContainerUnloadingNewJerseyRoute
  '/cross-dock-new-jersey': typeof CrossDockNewJerseyRoute
  '/fulfillment-new-jersey': typeof FulfillmentNewJerseyRoute
  '/markets': typeof MarketsRoute
  '/pallet-restacking-new-jersey': typeof PalletRestackingNewJerseyRoute
  '/pallet-storage-new-jersey': typeof PalletStorageNewJerseyRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminal-at-the-dock': typeof TerminalAtTheDockRoute
  '/terminal-at-the-gate': typeof TerminalAtTheGateRoute
  '/terminal-in-the-yard': typeof TerminalInTheYardRoute
  '/transloading-new-jersey': typeof TransloadingNewJerseyRoute
  '/what-is-terminal-yos': typeof WhatIsTerminalYosRoute
  '/api/quote': typeof ApiQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/container-unloading-new-jersey': typeof ContainerUnloadingNewJerseyRoute
  '/cross-dock-new-jersey': typeof CrossDockNewJerseyRoute
  '/fulfillment-new-jersey': typeof FulfillmentNewJerseyRoute
  '/markets': typeof MarketsRoute
  '/pallet-restacking-new-jersey': typeof PalletRestackingNewJerseyRoute
  '/pallet-storage-new-jersey': typeof PalletStorageNewJerseyRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminal-at-the-dock': typeof TerminalAtTheDockRoute
  '/terminal-at-the-gate': typeof TerminalAtTheGateRoute
  '/terminal-in-the-yard': typeof TerminalInTheYardRoute
  '/transloading-new-jersey': typeof TransloadingNewJerseyRoute
  '/what-is-terminal-yos': typeof WhatIsTerminalYosRoute
  '/api/quote': typeof ApiQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/container-unloading-new-jersey'
    | '/cross-dock-new-jersey'
    | '/fulfillment-new-jersey'
    | '/markets'
    | '/pallet-restacking-new-jersey'
    | '/pallet-storage-new-jersey'
    | '/quote'
    | '/resources'
    | '/sitemap.xml'
    | '/terminal-at-the-dock'
    | '/terminal-at-the-gate'
    | '/terminal-in-the-yard'
    | '/transloading-new-jersey'
    | '/what-is-terminal-yos'
    | '/api/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/container-unloading-new-jersey'
    | '/cross-dock-new-jersey'
    | '/fulfillment-new-jersey'
    | '/markets'
    | '/pallet-restacking-new-jersey'
    | '/pallet-storage-new-jersey'
    | '/quote'
    | '/resources'
    | '/sitemap.xml'
    | '/terminal-at-the-dock'
    | '/terminal-at-the-gate'
    | '/terminal-in-the-yard'
    | '/transloading-new-jersey'
    | '/what-is-terminal-yos'
    | '/api/quote'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/container-unloading-new-jersey'
    | '/cross-dock-new-jersey'
    | '/fulfillment-new-jersey'
    | '/markets'
    | '/pallet-restacking-new-jersey'
    | '/pallet-storage-new-jersey'
    | '/quote'
    | '/resources'
    | '/sitemap.xml'
    | '/terminal-at-the-dock'
    | '/terminal-at-the-gate'
    | '/terminal-in-the-yard'
    | '/transloading-new-jersey'
    | '/what-is-terminal-yos'
    | '/api/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ContainerUnloadingNewJerseyRoute: typeof ContainerUnloadingNewJerseyRoute
  CrossDockNewJerseyRoute: typeof CrossDockNewJerseyRoute
  FulfillmentNewJerseyRoute: typeof FulfillmentNewJerseyRoute
  MarketsRoute: typeof MarketsRoute
  PalletRestackingNewJerseyRoute: typeof PalletRestackingNewJerseyRoute
  PalletStorageNewJerseyRoute: typeof PalletStorageNewJerseyRoute
  QuoteRoute: typeof QuoteRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminalAtTheDockRoute: typeof TerminalAtTheDockRoute
  TerminalAtTheGateRoute: typeof TerminalAtTheGateRoute
  TerminalInTheYardRoute: typeof TerminalInTheYardRoute
  TransloadingNewJerseyRoute: typeof TransloadingNewJerseyRoute
  WhatIsTerminalYosRoute: typeof WhatIsTerminalYosRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/container-unloading-new-jersey': {
      id: '/container-unloading-new-jersey'
      path: '/container-unloading-new-jersey'
      fullPath: '/container-unloading-new-jersey'
      preLoaderRoute: typeof ContainerUnloadingNewJerseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-dock-new-jersey': {
      id: '/cross-dock-new-jersey'
      path: '/cross-dock-new-jersey'
      fullPath: '/cross-dock-new-jersey'
      preLoaderRoute: typeof CrossDockNewJerseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfillment-new-jersey': {
      id: '/fulfillment-new-jersey'
      path: '/fulfillment-new-jersey'
      fullPath: '/fulfillment-new-jersey'
      preLoaderRoute: typeof FulfillmentNewJerseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pallet-restacking-new-jersey': {
      id: '/pallet-restacking-new-jersey'
      path: '/pallet-restacking-new-jersey'
      fullPath: '/pallet-restacking-new-jersey'
      preLoaderRoute: typeof PalletRestackingNewJerseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pallet-storage-new-jersey': {
      id: '/pallet-storage-new-jersey'
      path: '/pallet-storage-new-jersey'
      fullPath: '/pallet-storage-new-jersey'
      preLoaderRoute: typeof PalletStorageNewJerseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal-at-the-dock': {
      id: '/terminal-at-the-dock'
      path: '/terminal-at-the-dock'
      fullPath: '/terminal-at-the-dock'
      preLoaderRoute: typeof TerminalAtTheDockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal-at-the-gate': {
      id: '/terminal-at-the-gate'
      path: '/terminal-at-the-gate'
      fullPath: '/terminal-at-the-gate'
      preLoaderRoute: typeof TerminalAtTheGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal-in-the-yard': {
      id: '/terminal-in-the-yard'
      path: '/terminal-in-the-yard'
      fullPath: '/terminal-in-the-yard'
      preLoaderRoute: typeof TerminalInTheYardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transloading-new-jersey': {
      id: '/transloading-new-jersey'
      path: '/transloading-new-jersey'
      fullPath: '/transloading-new-jersey'
      preLoaderRoute: typeof TransloadingNewJerseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-terminal-yos': {
      id: '/what-is-terminal-yos'
      path: '/what-is-terminal-yos'
      fullPath: '/what-is-terminal-yos'
      preLoaderRoute: typeof WhatIsTerminalYosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ContainerUnloadingNewJerseyRoute: ContainerUnloadingNewJerseyRoute,
  CrossDockNewJerseyRoute: CrossDockNewJerseyRoute,
  FulfillmentNewJerseyRoute: FulfillmentNewJerseyRoute,
  MarketsRoute: MarketsRoute,
  PalletRestackingNewJerseyRoute: PalletRestackingNewJerseyRoute,
  PalletStorageNewJerseyRoute: PalletStorageNewJerseyRoute,
  QuoteRoute: QuoteRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminalAtTheDockRoute: TerminalAtTheDockRoute,
  TerminalAtTheGateRoute: TerminalAtTheGateRoute,
  TerminalInTheYardRoute: TerminalInTheYardRoute,
  TransloadingNewJerseyRoute: TransloadingNewJerseyRoute,
  WhatIsTerminalYosRoute: WhatIsTerminalYosRoute,
  ApiQuoteRoute: ApiQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
